baseURL = "https://github.com/dangaiden/dangaiden.github.io"
languageCode = "en-us"
theme = "hugo-papermod"
title = "IT Gaiden"
paginate = 500 #frontpage pagination

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  header_image = "images/main_go_wideandtall_darklayer.jpeg"
  title = "Cloud SRE"
  slogan = "$ grep -rni \"The how's and why's\" ."
  SEOTitle = "IT Gaiden"
  keyword = "IT, it, kubernetes, devops, code, vmware, container, containers, linux, windows, cloud, cloud native"
 
  # Sidebar settings
  sidebar_about_description = "Gamer, cyclist guitarist and CloudSRE"
  #sidebar_avatar = "images/MeAtJackson.jpeg"
  about_me = true

  featured_tags = true 
  featured_condition_size = 2 # How many posts have to have a given tag to be featured (greater-than)

  image_404 = "images/404-bg.jpg"
  title_404 = "We couldn't find what you were looking for..."

  omit_categories = false

  [[params.addtional_menus]]
  title =  "ABOUT"
  href =  "/top/about/"

  [params.social]
  rss            = true
  #email         = "rich.youngkin@gmail.com"
  linkedin       = "https://www.linkedin.com/in/danielbelmonte/"
  github         = "https://github.com/dangaiden"
  twitter        = "https://twitter.com/DanGaiden"