

######Cleanwhite################

#baseURL = "https://dangaiden.github.io"
#languageCode = "en-us"
#theme = "cleanwhite"
#title = "Dan Belmonte"
#paginate = 6


# [markup]
#   [markup.goldmark]
#     [markup.goldmark.renderer]
#       unsafe = true

# [params]
#   header_image = "/static/itgaiden.jpeg"
#   title = "IT Gaiden"
#   slogan = "Tips. stories and more about the IT"
#   #env = production    
#   SEOTitle = "IT Gaiden"
#   keyword = "VMware, Windows, Kubernetes, Docker, SRE, DevOps, devops, Dan, Belmonte"
 
#   # Sidebar settings
#   sidebar_about_description = "I like road bikes (cyclist), playing videogames (gamer) and, anything related to tech!"
#   sidebar_avatar = "/static/profile.jpeg"
#   about_me = true

#   featured_tags = true 
#   featured_condition_size = 4 # How many posts have to have a given tag to be featured (greater-than)

#   #image_404 = "images/404-bg.jpg"
#   title_404 = "We couldn't find what you were looking for..."

#   omit_categories = false

#   [[params.addtional_menus]]
#   title =  "ABOUT"
#   href =  "/content/about-me/"

#   [params.social]
#   twitter       = "https://twitter.com/DanGaiden"
#   github        = "https://github.com/dangaiden"
#   linkedin      = "https://www.linkedin.com/in/danielbelmonte/"







######PAPER-MOD

baseURL : "https://dangaiden.github.io"
languageCode : "en-us"
theme : "papermod"
title : "Dan Belmonte"
paginate : 6


outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

params:
    relativeURLs : true
    defaultTheme: auto
    env: production    
    paginate : 6
    title : "Dan Belmonte"
    SEOTitle : "IT Gaiden"
    keyword : "VMware, Windows, Kubernetes, Docker, SRE, DevOps, devops, Dan, Belmonte"
    ShowCodeCopyButtons: true 
    ShowReadingTime: true
    ShowToc: true
    profileMode:
        enabled: true
        subtitle: "Tips. stories and more about IT"
        imageUrl: "/itgaiden.jpg" # optional
        #imageTitle: "<title of image as alt>" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
            - name: Posts
              url: "/content/posts/"
            - name: About me
              url: "/content/about-me/"

    socialIcons: # optional
       - name: Twitter   
         url: "https://twitter.com/DanGaiden"
       - name: Linkedin
         url: "https://www.linkedin.com/in/danielbelmonte/"
       - name: Github    
         url: "https://github.com/dangaiden"

menu:
    main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - identifier: categories
          name: categories
          url: /categories/
          weight: 15
        - identifier: tags
          name: tags
          url: /tags/
          weight: 20


#[params]
#	[[params.addtional_menus]]
#	title :  "ABOUT"
#	href :  "/content/about-me/"

#languages:
#    en:
#        languageName: "English"
#        weight: 1
#        menu:
#            main:
#                - name: Archive
#                  url: archives
#                  weight: 5
#                - name: Search
#                  url: search/
#                  weight: 10
#                - name: Tags
#                  url: tags/
#                  weight: 10
#                - name: Categories
#                  url: categories/
#                  weight: 10
